### ISSUE TITLE
Uncaught ReferenceError: br is not defined

### ISSUE THREAD

**Issue by ashutosh2k12** [svnpenn/bm#10]
It seems like the part of code clearly pulls out the signature function from asset's JS file but fails to execute the function. For ex, on this video https://www.youtube.com/watch?v=GFGPSx6cPN0 ,the bookmarklet fails to execute and returns the error as mentioned in title

**Comment by svnpenn** [comment]
> The uploader has not made this video available in your country.

If you can find an example that works in the US I will reopen

**Comment by ashutosh2k12** [comment]
here is one: https://www.youtube.com/watch?v=kPcDfLrzx3Y

**Comment by svnpenn** [comment]
@ashutosh2k12 I hardened the regex, let me know if it works for you

**Comment by ashutosh2k12** [comment]
Thank you. It worked purrfectly
