### ISSUE TITLE
No 60Hz YT support?

### ISSUE THREAD

**Issue by DizzyZane** [svnpenn/bm#11]
Mainly asking because it is quite annoying for 60Hz/60FPS videos, they lose a lot of their smoothness.

**Comment by svnpenn** [comment]
Post example link, and I will reopen

**Comment by DizzyZane** [comment]
https://www.youtube.com/watch?v=EIHyDn3BQ-I

I've tested all of the download options available, but none of them provide 60 FPS video. Not even 1440p.

**Comment by svnpenn** [comment]
Ah, I think I see the problem. I will try to fix it after work

**Comment by DizzyZane** [comment]
Thanks!
