### ISSUE TITLE
Bad signatures

### ISSUE THREAD

**Issue by sebstenza** [svnpenn/bm#12]
Hi,
The actual signatures are "null".
Is this because Youtube uses $x as variable names in base.js?

**Comment by svnpenn** [comment]
Provide example URL and I will reopen

**Comment by sebstenza** [comment]
I tried https://www.youtube.com/watch?v=YykjpeuMNEk and I got a signature=null

**Comment by svnpenn** [comment]
Works for me:

![coldplay](https://cloud.githubusercontent.com/assets/926619/14936569/d26edce0-0eb5-11e6-8509-28ee7fdfbeca.png)

**Comment by svnpenn** [comment]
Make sure you check the README for gotchas:

http://github.com/svnpenn/bm/blob/gh-pages/readme.md

**Comment by sebstenza** [comment]
It works with https://www.youtube.com/watch?v=eFP3uD_gXsQ but still not ok with Vevo clips like https://www.youtube.com/watch?v=YykjpeuMNEk

![](https://cloud.githubusercontent.com/assets/18749723/14940547/9a813dda-0f7a-11e6-8912-3e6545981fee.png)

**Comment by svnpenn** [comment]
It is failing for me too now, I will look into it

**Comment by svnpenn** [comment]
The problem is not the RegEx as I expected, but the proxy. You can they have a
quota now:

http://allow-any-origin.appspot.com

A workaround is to use another proxy, you will notice once is already listed:

http://github.com/svnpenn/bm/blob/8c823c4/yt-dl.js#L63

I think I have a permanent workaround that will no longer require a proxy, but
this will take some time.

**Comment by svnpenn** [comment]
After some tests, it looks like the new rate on Appspot is 5 requests per hour, pretty awful

**Comment by svnpenn** [comment]
@sebstenza check the new version

**Comment by sebstenza** [comment]
It works with english (US) language, but the base.js for french language still gives me a null signature :(

**Comment by svnpenn** [comment]
give example link or issue stays closed

**Comment by sebstenza** [comment]
Try https://www.youtube.com/watch?v=nYh-n7EOtMA with English US and French language. The sig is null in french.

**Comment by svnpenn** [comment]
Bookmarklet works on that link for me. Not sure what you mean by english and french. Also notice that I moved the bookmarklet recently, here is new URL:

https://svnpenn.github.io/bm/yt-dl/yt-dl.js

Make sure your bookmarklet is pointing to correct URL, or grab updated bookmarklet from:

https://svnpenn.github.io/bm

**Comment by sebstenza** [comment]
You can change Youtube language in the options at the bottom of the page. The base.js is different from a language to another with Youtube. My actual base.js is https://s.ytimg.com/yts/jsbin/player-fr_FR-vfloWes8s/base.js, and it still gives me a null signature with the actual bookmarklet.

**Comment by svnpenn** [comment]
I see the issue now, I will look into it

**Comment by svnpenn** [comment]
Your original suspicion was correct. Here is the English text:

    "signature",as(c)

Here is the French:

    "signature",$r(c)

My RegEx was assuming only letters for the function name:

http://github.com/svnpenn/bm/blob/a8f8e6b/yt-dl/yt-dl.js#L75

Should be an easy fix
