### ISSUE TITLE
Alert: "run bookmarklet again on next page"

### ISSUE THREAD

**Issue by pixelslivewallpaper** [svnpenn/bm#13]
Hi there.

I’m having some troubles here, it was working perfectly but suddenly I’m getting an error.

“run bookmarklet again on next page“

After click “OK” the site is redirected to https://s.ytimg.com/

Thanks

**Comment by svnpenn** [comment]
Provide example URL and I will reopen, thanks

**Comment by pixelslivewallpaper** [comment]
Hi.

It's happening in multiples URLs. 

https://www.youtube.com/watch?v=-pm5Bjf5eOc


Thanks.

**Comment by svnpenn** [comment]
A redirect is not need for all videos, but it is needed in this case, as that video uses an encrypted signature. The redirect is required to decrypt the signature. Previously we solved this problem with a CORS proxy, but I feel clicking the bookmarklet twice on certain videos is better than relying on a proxy.

Nothing to fix here.

**Comment by svnpenn** [comment]
I will think about how to make this more clear to the user

**Comment by svnpenn** [comment]
I am going to reopen this. Not to fix the issue per se, but to remind me to add something (readme, better alert, etc) to help with the confusion

**Comment by pixelslivewallpaper** [comment]
Thanks for the support.

**Comment by svnpenn** [comment]
@pixelslivewallpaper https://github.com/svnpenn/bm/commit/3c8b45ede39f37d7de2ac81d5d4032d03b1c474c closes this for now, although I will probably need to reopen it if I implement the download attribute:

http://github.com/svnpenn/bm/tree/142ad64/yt-dl#redirect-to-utilize-download-attribute
