### ISSUE TITLE
yt-dl: keys is not defined, deprecation warnings

### ISSUE THREAD

**Issue by calioptrix** [svnpenn/bm#26]
In Chrome for windows Version 59.0.3071.115 when attempting to use the bookmarklet, I get:

~~~
yt-dl.js:4 [Deprecation] 'webkitURL' is deprecated. Please use 'URL' instead.
flatten @ yt-dl.js:4
flatten @ yt-dl.js:8
[...]
(anonymous) @ yt-dl.js:22
yt-dl.js:4 [Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 
'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage'
instead.
flatten @ yt-dl.js:4
flatten @ yt-dl.js:8
[...]
(anonymous) @ yt-dl.js:22
rawgit.com/svnpenn/bm/master/yt-dl/yt-dl.js:15 Uncaught ReferenceError: keys is
not defined
    at flatten (rawgit.com/svnpenn/bm/master/yt-dl/yt-dl.js:15)
    at rawgit.com/svnpenn/bm/master/yt-dl/yt-dl.js:22
flatten @ rawgit.com/svnpenn/bm/master/yt-dl/yt-dl.js:15
(anonymous) @ rawgit.com/svnpenn/bm/master/yt-dl/yt-dl.js:22
~~~

**Comment by svnpenn** [comment]
provide example page and I will reopen

**Comment by calioptrix** [comment]
It happens for me on every video I've tried. 

https://www.youtube.com/watch?v=dSoXEtFPTfI
https://www.youtube.com/watch?v=YsA_JTeHJ6A
https://www.youtube.com/watch?v=JgQVj4iMm8Y
https://www.youtube.com/watch?v=CuVFcizDwqw
https://www.youtube.com/watch?v=ro2YUiAN_4s
https://www.youtube.com/watch?v=Iy7NzjCmUf0

**Comment by svnpenn** [comment]
I can repro this - I do have a fix for this but will probably not commit until saturday because of some personal stuff

**Comment by calioptrix** [comment]
When attempting to download now, it brings up a menu of video types to download. I've tried several and always get a 403 error.

When trying the first video I linked as 720p video/mp4, I get this:

Access to r6---sn-ab5szn7s.googlevideo.com was denied

You don't have authorization to view this page.
HTTP ERROR 403

**Comment by svnpenn** [comment]
All this time and it was one line to fix, hah
